In [2]:
import numpy as np
t = (2,3) #튜플로 주면 다차원 배열로 준다
x = np.zeros((2,5,5))
print(x)
x[0][0][2] = 5  # c 스타일
x[0,0,2] = 5    # 이렇게 하는 방법도 된다
x

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


array([[[0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
x.reshape(1,50) #1차원으로 변경

array([[0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [11]:
import numpy as np
np.array([i for i in range(0,100) if i%3==1]).reshape(3,11)

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31],
       [34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64],
       [67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]])

In [22]:
lol = np.array([i for i in range(0,20)]).reshape(4,5)
print(lol)
lol[1:3,2:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 7,  8],
       [12, 13]])

In [25]:
import math
math.sqrt(4)
np.sqrt(2)  # math로 안하고 np로 해도 된다

1.4142135623730951

In [28]:
a3 = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2,)
print(a3)
np.transpose(a3,(2,0,1)) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [9]:
#
import numpy as np
a = np.array([10,20,30,40,50,60,70])
b = a > 50
b
a[a > 50]


array([60, 70])

In [165]:
a = np.random.randint(100,201,size=10)
print(a)
a[a >= 150] = 200
print(a)

[123 174 150 141 121 183 180 107 122 186]
[123 200 200 141 121 200 200 107 122 200]


In [208]:
#카드게임? -> 총 54장(13*4 +2)
import numpy as np
import time
#1.
cardlist = np.array([i for i in range(1,55)])
np.random.shuffle(cardlist)
print(cardlist[:7])

#2. seed추가
np.random.seed(int(time.time()))
np.random.shuffle(cardlist)
print(cardlist[:7])


[35  6 24 27 25 53 44]
[14  4 45 42 12 36 53]


In [226]:
# 무슨 사이트에서 문제 50~59번 문제의 답을 문제번호와 함께 4개이상 답을 분리하여 
#50번 Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows
import numpy as np
a = np.array(np.random.randint(1,17,size=16)).reshape(4,4)
print(a)
b = a[0], a[-1] = a[-1], a[0]
print(b)

[[ 7  5 11  9]
 [13 11 14 15]
 [ 2  3 13 14]
 [16 10  6  9]]
(array([16, 10,  6,  9]), array([16, 10,  6,  9]))


In [216]:
#51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.
import numpy as np
np.zeros(shape=(5,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [223]:
#52. Write a NumPy program to sort a given array by row and column in ascending order.
import numpy as np
a = np.array(np.random.randint(1,17,size=16)).reshape(4,4)
print(np.sort(a))
print(np.sort(a,axis=1))

[[ 2  7 13 13]
 [ 5 10 13 13]
 [ 7 12 14 15]
 [ 2 11 12 15]]
[[ 2  7 13 13]
 [ 5 10 13 13]
 [ 7 12 14 15]
 [ 2 11 12 15]]


In [230]:
#59 
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a*b)



[1 4 9]
