In [6]:
#1.Write a NumPy program to get the numpy version and show numpy build configuration.
import numpy as np
print(np.version.version)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jay/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jay/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jay/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jay/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jay/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jay/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jay/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jay/opt/anaconda3/include']
None


In [12]:
#11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
x1 = np.array([1,2,3])
x2 = np.array([1,2,3])
x3 = np.array([4,5,6])
print(np.equal(x1,x2))
print(np.equal(x1,x3))


[ True  True  True]
[False False False]


In [37]:
#21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [23]:
#31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
print(np.random.randint(0,5,size=(3,3,3)))

[[[1 0 3]
  [1 1 4]
  [2 3 2]]

 [[1 4 0]
  [0 0 1]
  [1 1 4]]

 [[0 3 2]
  [3 0 4]
  [1 0 2]]]


In [34]:
#41. Write a NumPy program to convert numpy dtypes to native python types.
numpytype = np.float32(0)
print(type(numpytype))
print(type(numpytype.item()))


<class 'numpy.float32'>
<class 'float'>


In [36]:
#51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.
np.zeros(shape=(5,6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])